version: "3"

services:
  chroma:
    image: chromadb/chroma
    volumes:
      - ./data/chroma:/chroma/chroma
    ports:
      - 9000:8000
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
